server:
  port: 7001

eureka:
  instance:
    hostname: eureka-7001
  client:
    #是否将自己的信息注册到eruka
    register-with-eureka: false
    #是否从eurka中获取获取其它服务信息
    fetch-registry: false
    #注册中心地址 (单机指向自己，集群指向其它)
    service-url:
      defaultZone: http://eureka02:7002/eureka

spring:
  application:
    name: spring-eureka-7001
