server:
  port: 80
  servlet:
    context-path: /consumer

spring:
  application:
    name: cloud-consumer-order80
  zipkin:
    base-url: http://132.232.77.49:9411
    sleuth:
      sampler:
      ## 采样率 0-1之间  1表示每条请求都记录
      probability: 1
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka # 单个eureka
      #集群版
      defaultZone: http://eureka01:7001/eureka,http://eureka02:7002/eureka
    fetch-registry: true
    register-with-eureka: true
