server:
  port: 8006

spring:
  application:
    name: provider-consul-payment8006
  cloud:
    #注册中心配置
    consul:
      host: 132.232.77.49
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
